#pragma once
#include <cstdint>

namespace Lust
{
	using KeyCode = uint16_t;

	namespace Key
	{
		enum : KeyCode
		{
            LUST_KEYCODE_UNKNOWN = 0,

            LUST_KEYCODE_A = 4,
            LUST_KEYCODE_B = 5,
            LUST_KEYCODE_C = 6,
            LUST_KEYCODE_D = 7,
            LUST_KEYCODE_E = 8,
            LUST_KEYCODE_F = 9,
            LUST_KEYCODE_G = 10,
            LUST_KEYCODE_H = 11,
            LUST_KEYCODE_I = 12,
            LUST_KEYCODE_J = 13,
            LUST_KEYCODE_K = 14,
            LUST_KEYCODE_L = 15,
            LUST_KEYCODE_M = 16,
            LUST_KEYCODE_N = 17,
            LUST_KEYCODE_O = 18,
            LUST_KEYCODE_P = 19,
            LUST_KEYCODE_Q = 20,
            LUST_KEYCODE_R = 21,
            LUST_KEYCODE_S = 22,
            LUST_KEYCODE_T = 23,
            LUST_KEYCODE_U = 24,
            LUST_KEYCODE_V = 25,
            LUST_KEYCODE_W = 26,
            LUST_KEYCODE_X = 27,
            LUST_KEYCODE_Y = 28,
            LUST_KEYCODE_Z = 29,

            LUST_KEYCODE_1 = 30,
            LUST_KEYCODE_2 = 31,
            LUST_KEYCODE_3 = 32,
            LUST_KEYCODE_4 = 33,
            LUST_KEYCODE_5 = 34,
            LUST_KEYCODE_6 = 35,
            LUST_KEYCODE_7 = 36,
            LUST_KEYCODE_8 = 37,
            LUST_KEYCODE_9 = 38,
            LUST_KEYCODE_0 = 39,

            LUST_KEYCODE_RETURN = 40,
            LUST_KEYCODE_ESCAPE = 41,
            LUST_KEYCODE_BACKSPACE = 42,
            LUST_KEYCODE_TAB = 43,
            LUST_KEYCODE_SPACE = 44,

            LUST_KEYCODE_MINUS = 45,
            LUST_KEYCODE_EQUALS = 46,
            LUST_KEYCODE_LEFTBRACKET = 47,
            LUST_KEYCODE_RIGHTBRACKET = 48,
            LUST_KEYCODE_BACKSLASH = 49, 
            LUST_KEYCODE_NONUSHASH = 50,
            LUST_KEYCODE_SEMICOLON = 51,
            LUST_KEYCODE_APOSTROPHE = 52,
            LUST_KEYCODE_GRAVE = 53,
            LUST_KEYCODE_COMMA = 54,
            LUST_KEYCODE_PERIOD = 55,
            LUST_KEYCODE_SLASH = 56,

            LUST_KEYCODE_CAPSLOCK = 57,

            LUST_KEYCODE_F1 = 58,
            LUST_KEYCODE_F2 = 59,
            LUST_KEYCODE_F3 = 60,
            LUST_KEYCODE_F4 = 61,
            LUST_KEYCODE_F5 = 62,
            LUST_KEYCODE_F6 = 63,
            LUST_KEYCODE_F7 = 64,
            LUST_KEYCODE_F8 = 65,
            LUST_KEYCODE_F9 = 66,
            LUST_KEYCODE_F10 = 67,
            LUST_KEYCODE_F11 = 68,
            LUST_KEYCODE_F12 = 69,

            LUST_KEYCODE_PRINTSCREEN = 70,
            LUST_KEYCODE_SCROLLLOCK = 71,
            LUST_KEYCODE_PAUSE = 72,
            LUST_KEYCODE_INSERT = 73,
            LUST_KEYCODE_HOME = 74,
            LUST_KEYCODE_PAGEUP = 75,
            LUST_KEYCODE_DELETE = 76,
            LUST_KEYCODE_END = 77,
            LUST_KEYCODE_PAGEDOWN = 78,
            LUST_KEYCODE_RIGHT = 79,
            LUST_KEYCODE_LEFT = 80,
            LUST_KEYCODE_DOWN = 81,
            LUST_KEYCODE_UP = 82,

            LUST_KEYCODE_NUMLOCKCLEAR = 83,
            LUST_KEYCODE_KP_DIVIDE = 84,
            LUST_KEYCODE_KP_MULTIPLY = 85,
            LUST_KEYCODE_KP_MINUS = 86,
            LUST_KEYCODE_KP_PLUS = 87,
            LUST_KEYCODE_KP_ENTER = 88,
            LUST_KEYCODE_KP_1 = 89,
            LUST_KEYCODE_KP_2 = 90,
            LUST_KEYCODE_KP_3 = 91,
            LUST_KEYCODE_KP_4 = 92,
            LUST_KEYCODE_KP_5 = 93,
            LUST_KEYCODE_KP_6 = 94,
            LUST_KEYCODE_KP_7 = 95,
            LUST_KEYCODE_KP_8 = 96,
            LUST_KEYCODE_KP_9 = 97,
            LUST_KEYCODE_KP_0 = 98,
            LUST_KEYCODE_KP_PERIOD = 99,

            LUST_KEYCODE_NONUSBACKSLASH = 100,
            LUST_KEYCODE_APPLICATION = 101,
            LUST_KEYCODE_POWER = 102,
            LUST_KEYCODE_KP_EQUALS = 103,
            LUST_KEYCODE_F13 = 104,
            LUST_KEYCODE_F14 = 105,
            LUST_KEYCODE_F15 = 106,
            LUST_KEYCODE_F16 = 107,
            LUST_KEYCODE_F17 = 108,
            LUST_KEYCODE_F18 = 109,
            LUST_KEYCODE_F19 = 110,
            LUST_KEYCODE_F20 = 111,
            LUST_KEYCODE_F21 = 112,
            LUST_KEYCODE_F22 = 113,
            LUST_KEYCODE_F23 = 114,
            LUST_KEYCODE_F24 = 115,
            LUST_KEYCODE_EXECUTE = 116,
            LUST_KEYCODE_HELP = 117,    
            LUST_KEYCODE_MENU = 118,
            LUST_KEYCODE_SELECT = 119,
            LUST_KEYCODE_STOP = 120,
            LUST_KEYCODE_AGAIN = 121,
            LUST_KEYCODE_UNDO = 122,
            LUST_KEYCODE_CUT = 123,
            LUST_KEYCODE_COPY = 124,
            LUST_KEYCODE_PASTE = 125,
            LUST_KEYCODE_FIND = 126,
            LUST_KEYCODE_MUTE = 127,
            LUST_KEYCODE_VOLUMEUP = 128,
            LUST_KEYCODE_VOLUMEDOWN = 129,
            LUST_KEYCODE_KP_COMMA = 133,
            LUST_KEYCODE_KP_EQUALSAS400 = 134,
            LUST_KEYCODE_INTERNATIONAL1 = 135,
            LUST_KEYCODE_INTERNATIONAL2 = 136,
            LUST_KEYCODE_INTERNATIONAL3 = 137,
            LUST_KEYCODE_INTERNATIONAL4 = 138,
            LUST_KEYCODE_INTERNATIONAL5 = 139,
            LUST_KEYCODE_INTERNATIONAL6 = 140,
            LUST_KEYCODE_INTERNATIONAL7 = 141,
            LUST_KEYCODE_INTERNATIONAL8 = 142,
            LUST_KEYCODE_INTERNATIONAL9 = 143,
            LUST_KEYCODE_LANG1 = 144,
            LUST_KEYCODE_LANG2 = 145,
            LUST_KEYCODE_LANG3 = 146,
            LUST_KEYCODE_LANG4 = 147,
            LUST_KEYCODE_LANG5 = 148,
            LUST_KEYCODE_LANG6 = 149,
            LUST_KEYCODE_LANG7 = 150,
            LUST_KEYCODE_LANG8 = 151,
            LUST_KEYCODE_LANG9 = 152,
            LUST_KEYCODE_ALTERASE = 153,
            LUST_KEYCODE_SYSREQ = 154,
            LUST_KEYCODE_CANCEL = 155,
            LUST_KEYCODE_CLEAR = 156,
            LUST_KEYCODE_PRIOR = 157,
            LUST_KEYCODE_RETURN2 = 158,
            LUST_KEYCODE_SEPARATOR = 159,
            LUST_KEYCODE_OUT = 160,
            LUST_KEYCODE_OPER = 161,
            LUST_KEYCODE_CLEARAGAIN = 162,
            LUST_KEYCODE_CRSEL = 163,
            LUST_KEYCODE_EXSEL = 164,

            LUST_KEYCODE_KP_00 = 176,
            LUST_KEYCODE_KP_000 = 177,
            LUST_KEYCODE_THOUSANDSSEPARATOR = 178,
            LUST_KEYCODE_DECIMALSEPARATOR = 179,
            LUST_KEYCODE_CURRENCYUNIT = 180,
            LUST_KEYCODE_CURRENCYSUBUNIT = 181,
            LUST_KEYCODE_KP_LEFTPAREN = 182,
            LUST_KEYCODE_KP_RIGHTPAREN = 183,
            LUST_KEYCODE_KP_LEFTBRACE = 184,
            LUST_KEYCODE_KP_RIGHTBRACE = 185,
            LUST_KEYCODE_KP_TAB = 186,
            LUST_KEYCODE_KP_BACKSPACE = 187,
            LUST_KEYCODE_KP_A = 188,
            LUST_KEYCODE_KP_B = 189,
            LUST_KEYCODE_KP_C = 190,
            LUST_KEYCODE_KP_D = 191,
            LUST_KEYCODE_KP_E = 192,
            LUST_KEYCODE_KP_F = 193,
            LUST_KEYCODE_KP_XOR = 194,
            LUST_KEYCODE_KP_POWER = 195,
            LUST_KEYCODE_KP_PERCENT = 196,
            LUST_KEYCODE_KP_LESS = 197,
            LUST_KEYCODE_KP_GREATER = 198,
            LUST_KEYCODE_KP_AMPERSAND = 199,
            LUST_KEYCODE_KP_DBLAMPERSAND = 200,
            LUST_KEYCODE_KP_VERTICALBAR = 201,
            LUST_KEYCODE_KP_DBLVERTICALBAR = 202,
            LUST_KEYCODE_KP_COLON = 203,
            LUST_KEYCODE_KP_HASH = 204,
            LUST_KEYCODE_KP_SPACE = 205,
            LUST_KEYCODE_KP_AT = 206,
            LUST_KEYCODE_KP_EXCLAM = 207,
            LUST_KEYCODE_KP_MEMSTORE = 208,
            LUST_KEYCODE_KP_MEMRECALL = 209,
            LUST_KEYCODE_KP_MEMCLEAR = 210,
            LUST_KEYCODE_KP_MEMADD = 211,
            LUST_KEYCODE_KP_MEMSUBTRACT = 212,
            LUST_KEYCODE_KP_MEMMULTIPLY = 213,
            LUST_KEYCODE_KP_MEMDIVIDE = 214,
            LUST_KEYCODE_KP_PLUSMINUS = 215,
            LUST_KEYCODE_KP_CLEAR = 216,
            LUST_KEYCODE_KP_CLEARENTRY = 217,
            LUST_KEYCODE_KP_BINARY = 218,
            LUST_KEYCODE_KP_OCTAL = 219,
            LUST_KEYCODE_KP_DECIMAL = 220,
            LUST_KEYCODE_KP_HEXADECIMAL = 221,

            LUST_KEYCODE_LCTRL = 224,
            LUST_KEYCODE_LSHIFT = 225,
            LUST_KEYCODE_LALT = 226,
            LUST_KEYCODE_LGUI = 227,
            LUST_KEYCODE_RCTRL = 228,
            LUST_KEYCODE_RSHIFT = 229,
            LUST_KEYCODE_RALT = 230,
            LUST_KEYCODE_RGUI = 231,
		};
	}
}