#include "VKFunctions.hpp"

#undef VK_NO_PROTOTYPES
#include <vulkan/vulkan_core.h>

bool Lust::VKFunctions::s_IsLoaded = false;

#ifdef LUST_USES_WINDOWS
PFN_vkCreateWin32SurfaceKHR Lust::VKFunctions::vkCreateWin32SurfaceKHRFn;
#endif

PFN_vkGetPhysicalDeviceFeatures Lust::VKFunctions::vkGetPhysicalDeviceFeaturesFn;
PFN_vkCmdDrawIndexed Lust::VKFunctions::vkCmdDrawIndexedFn;
PFN_vkCmdDraw Lust::VKFunctions::vkCmdDrawFn;
PFN_vkDestroySurfaceKHR Lust::VKFunctions::vkDestroySurfaceKHRFn;
PFN_vkCreateBuffer Lust::VKFunctions::vkCreateBufferFn;
PFN_vkGetBufferMemoryRequirements Lust::VKFunctions::vkGetBufferMemoryRequirementsFn;
PFN_vkAllocateMemory Lust::VKFunctions::vkAllocateMemoryFn;
PFN_vkBindBufferMemory Lust::VKFunctions::vkBindBufferMemoryFn;
PFN_vkAllocateCommandBuffers Lust::VKFunctions::vkAllocateCommandBuffersFn;
PFN_vkBeginCommandBuffer Lust::VKFunctions::vkBeginCommandBufferFn;
PFN_vkCmdCopyBuffer Lust::VKFunctions::vkCmdCopyBufferFn;
PFN_vkEndCommandBuffer Lust::VKFunctions::vkEndCommandBufferFn;
PFN_vkQueueSubmit Lust::VKFunctions::vkQueueSubmitFn;
PFN_vkQueueWaitIdle Lust::VKFunctions::vkQueueWaitIdleFn;
PFN_vkFreeCommandBuffers Lust::VKFunctions::vkFreeCommandBuffersFn;
PFN_vkMapMemory Lust::VKFunctions::vkMapMemoryFn;
PFN_vkUnmapMemory Lust::VKFunctions::vkUnmapMemoryFn;
PFN_vkGetPhysicalDeviceMemoryProperties Lust::VKFunctions::vkGetPhysicalDeviceMemoryPropertiesFn;
PFN_vkDeviceWaitIdle Lust::VKFunctions::vkDeviceWaitIdleFn;
PFN_vkDestroyBuffer Lust::VKFunctions::vkDestroyBufferFn;
PFN_vkFreeMemory Lust::VKFunctions::vkFreeMemoryFn;
PFN_vkCmdBindVertexBuffers Lust::VKFunctions::vkCmdBindVertexBuffersFn;
PFN_vkCmdBindIndexBuffer Lust::VKFunctions::vkCmdBindIndexBufferFn;
PFN_vkEnumerateInstanceLayerProperties Lust::VKFunctions::vkEnumerateInstanceLayerPropertiesFn;
PFN_vkDestroyFence Lust::VKFunctions::vkDestroyFenceFn;
PFN_vkDestroySemaphore Lust::VKFunctions::vkDestroySemaphoreFn;
PFN_vkDestroyCommandPool Lust::VKFunctions::vkDestroyCommandPoolFn;
PFN_vkDestroyRenderPass Lust::VKFunctions::vkDestroyRenderPassFn;
PFN_vkDestroyDevice Lust::VKFunctions::vkDestroyDeviceFn;
PFN_vkGetInstanceProcAddr Lust::VKFunctions::vkGetInstanceProcAddrFn;
PFN_vkDestroyInstance Lust::VKFunctions::vkDestroyInstanceFn;
PFN_vkCmdBeginRenderPass Lust::VKFunctions::vkCmdBeginRenderPassFn;
PFN_vkCmdEndRenderPass Lust::VKFunctions::vkCmdEndRenderPassFn;
PFN_vkWaitForFences Lust::VKFunctions::vkWaitForFencesFn;
PFN_vkAcquireNextImageKHR Lust::VKFunctions::vkAcquireNextImageKHRFn;
PFN_vkResetFences Lust::VKFunctions::vkResetFencesFn;
PFN_vkResetCommandBuffer Lust::VKFunctions::vkResetCommandBufferFn;
PFN_vkQueuePresentKHR Lust::VKFunctions::vkQueuePresentKHRFn;
PFN_vkCmdSetViewport Lust::VKFunctions::vkCmdSetViewportFn;
PFN_vkCmdSetScissor Lust::VKFunctions::vkCmdSetScissorFn;
PFN_vkGetPhysicalDeviceProperties Lust::VKFunctions::vkGetPhysicalDevicePropertiesFn;
PFN_vkCreateInstance Lust::VKFunctions::vkCreateInstanceFn;
PFN_vkEnumeratePhysicalDevices Lust::VKFunctions::vkEnumeratePhysicalDevicesFn;
PFN_vkGetPhysicalDeviceQueueFamilyProperties Lust::VKFunctions::vkGetPhysicalDeviceQueueFamilyPropertiesFn;
PFN_vkGetPhysicalDeviceSurfaceSupportKHR Lust::VKFunctions::vkGetPhysicalDeviceSurfaceSupportKHRFn;
PFN_vkEnumerateDeviceExtensionProperties Lust::VKFunctions::vkEnumerateDeviceExtensionPropertiesFn;
PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR Lust::VKFunctions::vkGetPhysicalDeviceSurfaceCapabilitiesKHRFn;
PFN_vkGetPhysicalDeviceSurfaceFormatsKHR Lust::VKFunctions::vkGetPhysicalDeviceSurfaceFormatsKHRFn;
PFN_vkGetPhysicalDeviceSurfacePresentModesKHR Lust::VKFunctions::vkGetPhysicalDeviceSurfacePresentModesKHRFn;
PFN_vkCreateDevice Lust::VKFunctions::vkCreateDeviceFn;
PFN_vkGetDeviceQueue Lust::VKFunctions::vkGetDeviceQueueFn;
PFN_vkCreateSwapchainKHR Lust::VKFunctions::vkCreateSwapchainKHRFn;
PFN_vkGetSwapchainImagesKHR Lust::VKFunctions::vkGetSwapchainImagesKHRFn;
PFN_vkDestroySwapchainKHR Lust::VKFunctions::vkDestroySwapchainKHRFn;
PFN_vkCreateImageView Lust::VKFunctions::vkCreateImageViewFn;
PFN_vkDestroyImageView Lust::VKFunctions::vkDestroyImageViewFn;
PFN_vkCreateRenderPass Lust::VKFunctions::vkCreateRenderPassFn;
PFN_vkCreateFramebuffer Lust::VKFunctions::vkCreateFramebufferFn;
PFN_vkDestroyFramebuffer Lust::VKFunctions::vkDestroyFramebufferFn;
PFN_vkCreateImage Lust::VKFunctions::vkCreateImageFn;
PFN_vkGetImageMemoryRequirements Lust::VKFunctions::vkGetImageMemoryRequirementsFn;
PFN_vkBindImageMemory Lust::VKFunctions::vkBindImageMemoryFn;
PFN_vkDestroyImage Lust::VKFunctions::vkDestroyImageFn;
PFN_vkCreateCommandPool Lust::VKFunctions::vkCreateCommandPoolFn;
PFN_vkCreateSemaphore Lust::VKFunctions::vkCreateSemaphoreFn;
PFN_vkCreateFence Lust::VKFunctions::vkCreateFenceFn;
PFN_vkCreatePipelineLayout Lust::VKFunctions::vkCreatePipelineLayoutFn;
PFN_vkCreateGraphicsPipelines Lust::VKFunctions::vkCreateGraphicsPipelinesFn;
PFN_vkDestroyShaderModule Lust::VKFunctions::vkDestroyShaderModuleFn;
PFN_vkDestroyDescriptorPool Lust::VKFunctions::vkDestroyDescriptorPoolFn;
PFN_vkDestroyDescriptorSetLayout Lust::VKFunctions::vkDestroyDescriptorSetLayoutFn;
PFN_vkDestroyPipeline Lust::VKFunctions::vkDestroyPipelineFn;
PFN_vkDestroyPipelineLayout Lust::VKFunctions::vkDestroyPipelineLayoutFn;
PFN_vkCmdBindPipeline Lust::VKFunctions::vkCmdBindPipelineFn;
PFN_vkCmdPushConstants Lust::VKFunctions::vkCmdPushConstantsFn;
PFN_vkCmdBindDescriptorSets Lust::VKFunctions::vkCmdBindDescriptorSetsFn;
PFN_vkUpdateDescriptorSets Lust::VKFunctions::vkUpdateDescriptorSetsFn;
PFN_vkAllocateDescriptorSets Lust::VKFunctions::vkAllocateDescriptorSetsFn;
PFN_vkCreateDescriptorSetLayout Lust::VKFunctions::vkCreateDescriptorSetLayoutFn;
PFN_vkCreateDescriptorPool Lust::VKFunctions::vkCreateDescriptorPoolFn;
PFN_vkCreateShaderModule Lust::VKFunctions::vkCreateShaderModuleFn;
PFN_vkCreateQueryPool Lust::VKFunctions::vkCreateQueryPoolFn;
PFN_vkDestroyQueryPool Lust::VKFunctions::vkDestroyQueryPoolFn;
PFN_vkCmdResetQueryPool Lust::VKFunctions::vkCmdResetQueryPoolFn;
PFN_vkCmdWriteTimestamp2 Lust::VKFunctions::vkCmdWriteTimestamp2Fn;
PFN_vkGetQueryPoolResults Lust::VKFunctions::vkGetQueryPoolResultsFn;
PFN_vkCreateSampler Lust::VKFunctions::vkCreateSamplerFn;
PFN_vkDestroySampler Lust::VKFunctions::vkDestroySamplerFn;
PFN_vkCmdPipelineBarrier Lust::VKFunctions::vkCmdPipelineBarrierFn;
PFN_vkCmdCopyBufferToImage Lust::VKFunctions::vkCmdCopyBufferToImageFn;

void Lust::VKFunctions::LoadVulkanFunctions()
{
	if(s_IsLoaded)
		return;
#ifdef LUST_USES_WINDOWS
	vkCreateWin32SurfaceKHRFn = vkCreateWin32SurfaceKHR;
#endif
	
	vkGetPhysicalDeviceFeaturesFn = vkGetPhysicalDeviceFeatures;
	vkCmdDrawIndexedFn = vkCmdDrawIndexed;
	vkCmdDrawFn = vkCmdDraw;
	vkDestroySurfaceKHRFn = vkDestroySurfaceKHR;
	vkCreateBufferFn = vkCreateBuffer;
	vkGetBufferMemoryRequirementsFn = vkGetBufferMemoryRequirements;
	vkAllocateMemoryFn = vkAllocateMemory;
	vkBindBufferMemoryFn = vkBindBufferMemory;
	vkAllocateCommandBuffersFn = vkAllocateCommandBuffers;
	vkBeginCommandBufferFn = vkBeginCommandBuffer;
	vkCmdCopyBufferFn = vkCmdCopyBuffer;
	vkEndCommandBufferFn = vkEndCommandBuffer;
	vkQueueSubmitFn = vkQueueSubmit;
	vkQueueWaitIdleFn = vkQueueWaitIdle;
	vkFreeCommandBuffersFn = vkFreeCommandBuffers;
	vkMapMemoryFn = vkMapMemory;
	vkUnmapMemoryFn = vkUnmapMemory;
	vkGetPhysicalDeviceMemoryPropertiesFn = vkGetPhysicalDeviceMemoryProperties;
	vkDeviceWaitIdleFn = vkDeviceWaitIdle;
	vkDestroyBufferFn = vkDestroyBuffer;
	vkFreeMemoryFn = vkFreeMemory;
	vkCmdBindVertexBuffersFn = vkCmdBindVertexBuffers;
	vkCmdBindIndexBufferFn = vkCmdBindIndexBuffer;
	vkEnumerateInstanceLayerPropertiesFn = vkEnumerateInstanceLayerProperties;
	vkDestroyFenceFn = vkDestroyFence;
	vkDestroySemaphoreFn = vkDestroySemaphore;
	vkDestroyCommandPoolFn = vkDestroyCommandPool;
	vkDestroyRenderPassFn = vkDestroyRenderPass;
	vkDestroyDeviceFn = vkDestroyDevice;
	vkGetInstanceProcAddrFn = vkGetInstanceProcAddr;
	vkDestroyInstanceFn = vkDestroyInstance;
	vkCmdBeginRenderPassFn = vkCmdBeginRenderPass;
	vkCmdEndRenderPassFn = vkCmdEndRenderPass;
	vkWaitForFencesFn = vkWaitForFences;
	vkAcquireNextImageKHRFn = vkAcquireNextImageKHR;
	vkResetFencesFn = vkResetFences;
	vkResetCommandBufferFn = vkResetCommandBuffer;
	vkQueuePresentKHRFn = vkQueuePresentKHR;
	vkCmdSetViewportFn = vkCmdSetViewport;
	vkCmdSetScissorFn = vkCmdSetScissor;
	vkGetPhysicalDevicePropertiesFn = vkGetPhysicalDeviceProperties;
	vkCreateInstanceFn = vkCreateInstance;
	vkEnumeratePhysicalDevicesFn = vkEnumeratePhysicalDevices;
	vkGetPhysicalDeviceQueueFamilyPropertiesFn = vkGetPhysicalDeviceQueueFamilyProperties;
	vkGetPhysicalDeviceSurfaceSupportKHRFn = vkGetPhysicalDeviceSurfaceSupportKHR;
	vkEnumerateDeviceExtensionPropertiesFn = vkEnumerateDeviceExtensionProperties;
	vkGetPhysicalDeviceSurfaceCapabilitiesKHRFn = vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
	vkGetPhysicalDeviceSurfaceFormatsKHRFn = vkGetPhysicalDeviceSurfaceFormatsKHR;
	vkGetPhysicalDeviceSurfacePresentModesKHRFn = vkGetPhysicalDeviceSurfacePresentModesKHR;
	vkCreateDeviceFn = vkCreateDevice;
	vkGetDeviceQueueFn = vkGetDeviceQueue;
	vkCreateSwapchainKHRFn = vkCreateSwapchainKHR;
	vkGetSwapchainImagesKHRFn = vkGetSwapchainImagesKHR;
	vkDestroySwapchainKHRFn = vkDestroySwapchainKHR;
	vkCreateImageViewFn = vkCreateImageView;
	vkDestroyImageViewFn = vkDestroyImageView;
	vkCreateRenderPassFn = vkCreateRenderPass;
	vkCreateFramebufferFn = vkCreateFramebuffer;
	vkDestroyFramebufferFn = vkDestroyFramebuffer;
	vkCreateImageFn = vkCreateImage;
	vkGetImageMemoryRequirementsFn = vkGetImageMemoryRequirements;
	vkBindImageMemoryFn = vkBindImageMemory;
	vkDestroyImageFn = vkDestroyImage;
	vkCreateCommandPoolFn = vkCreateCommandPool;
	vkCreateSemaphoreFn = vkCreateSemaphore;
	vkCreateFenceFn = vkCreateFence;
	vkCreatePipelineLayoutFn = vkCreatePipelineLayout;
	vkCreateGraphicsPipelinesFn = vkCreateGraphicsPipelines;
	vkDestroyShaderModuleFn = vkDestroyShaderModule;
	vkDestroyDescriptorPoolFn = vkDestroyDescriptorPool;
	vkDestroyDescriptorSetLayoutFn = vkDestroyDescriptorSetLayout;
	vkDestroyPipelineFn = vkDestroyPipeline;
	vkDestroyPipelineLayoutFn = vkDestroyPipelineLayout;
	vkCmdBindPipelineFn = vkCmdBindPipeline;
	vkCmdPushConstantsFn = vkCmdPushConstants;
	vkCmdBindDescriptorSetsFn = vkCmdBindDescriptorSets;
	vkUpdateDescriptorSetsFn = vkUpdateDescriptorSets;
	vkAllocateDescriptorSetsFn = vkAllocateDescriptorSets;
	vkCreateDescriptorSetLayoutFn = vkCreateDescriptorSetLayout;
	vkCreateDescriptorPoolFn = vkCreateDescriptorPool;
	vkCreateShaderModuleFn = vkCreateShaderModule;
	vkCreateQueryPoolFn = vkCreateQueryPool;
	vkDestroyQueryPoolFn = vkDestroyQueryPool;
	vkCmdResetQueryPoolFn =	vkCmdResetQueryPool;
	vkCmdWriteTimestamp2Fn = vkCmdWriteTimestamp2;
	vkGetQueryPoolResultsFn = vkGetQueryPoolResults;
	vkCreateSamplerFn = vkCreateSampler;
	vkDestroySamplerFn = vkDestroySampler;
	vkCmdPipelineBarrierFn = vkCmdPipelineBarrier;
	vkCmdCopyBufferToImageFn = vkCmdCopyBufferToImage;

	s_IsLoaded = true;
}

void Lust::VKFunctions::UnloadVulkanFunctions()
{
	if (!s_IsLoaded)
		return;
#ifdef LUST_USES_WINDOWS
	vkCreateWin32SurfaceKHRFn = nullptr;
#endif
	
	vkGetPhysicalDeviceFeaturesFn = nullptr;
	vkCmdDrawIndexedFn = nullptr;
	vkCmdDrawFn = nullptr;
	vkDestroySurfaceKHRFn = nullptr;
	vkCreateBufferFn = nullptr;
	vkGetBufferMemoryRequirementsFn = nullptr;
	vkAllocateMemoryFn = nullptr;
	vkBindBufferMemoryFn = nullptr;
	vkAllocateCommandBuffersFn = nullptr;
	vkBeginCommandBufferFn = nullptr;
	vkCmdCopyBufferFn = nullptr;
	vkEndCommandBufferFn = nullptr;
	vkQueueSubmitFn = nullptr;
	vkQueueWaitIdleFn = nullptr;
	vkFreeCommandBuffersFn = nullptr;
	vkMapMemoryFn = nullptr;
	vkUnmapMemoryFn = nullptr;
	vkGetPhysicalDeviceMemoryPropertiesFn = nullptr;
	vkDeviceWaitIdleFn = nullptr;
	vkDestroyBufferFn = nullptr;
	vkFreeMemoryFn = nullptr;
	vkCmdBindVertexBuffersFn = nullptr;
	vkCmdBindIndexBufferFn = nullptr;
	vkEnumerateInstanceLayerPropertiesFn = nullptr;
	vkDestroyFenceFn = nullptr;
	vkDestroySemaphoreFn = nullptr;
	vkDestroyCommandPoolFn = nullptr;
	vkDestroyRenderPassFn = nullptr;
	vkDestroyDeviceFn = nullptr;
	vkGetInstanceProcAddrFn = nullptr;
	vkDestroyInstanceFn = nullptr;
	vkCmdBeginRenderPassFn = nullptr;
	vkCmdEndRenderPassFn = nullptr;
	vkWaitForFencesFn = nullptr;
	vkAcquireNextImageKHRFn = nullptr;
	vkResetFencesFn = nullptr;
	vkResetCommandBufferFn = nullptr;
	vkQueuePresentKHRFn = nullptr;
	vkCmdSetViewportFn = nullptr;
	vkCmdSetScissorFn = nullptr;
	vkGetPhysicalDevicePropertiesFn = nullptr;
	vkCreateInstanceFn = nullptr;
	vkEnumeratePhysicalDevicesFn = nullptr;
	vkGetPhysicalDeviceQueueFamilyPropertiesFn = nullptr;
	vkGetPhysicalDeviceSurfaceSupportKHRFn = nullptr;
	vkEnumerateDeviceExtensionPropertiesFn = nullptr;
	vkGetPhysicalDeviceSurfaceCapabilitiesKHRFn = nullptr;
	vkGetPhysicalDeviceSurfaceFormatsKHRFn = nullptr;
	vkGetPhysicalDeviceSurfacePresentModesKHRFn = nullptr;
	vkCreateDeviceFn = nullptr;
	vkGetDeviceQueueFn = nullptr;
	vkCreateSwapchainKHRFn = nullptr;
	vkGetSwapchainImagesKHRFn = nullptr;
	vkDestroySwapchainKHRFn = nullptr;
	vkCreateImageViewFn = nullptr;
	vkDestroyImageViewFn = nullptr;
	vkCreateRenderPassFn = nullptr;
	vkCreateFramebufferFn = nullptr;
	vkDestroyFramebufferFn = nullptr;
	vkCreateImageFn = nullptr;
	vkGetImageMemoryRequirementsFn = nullptr;
	vkBindImageMemoryFn = nullptr;
	vkDestroyImageFn = nullptr;
	vkCreateCommandPoolFn = nullptr;
	vkCreateSemaphoreFn = nullptr;
	vkCreateFenceFn = nullptr;
	vkCreatePipelineLayoutFn = nullptr;
	vkCreateGraphicsPipelinesFn = nullptr;
	vkDestroyShaderModuleFn = nullptr;
	vkDestroyDescriptorPoolFn = nullptr;
	vkDestroyDescriptorSetLayoutFn = nullptr;
	vkDestroyPipelineFn = nullptr;
	vkDestroyPipelineLayoutFn = nullptr;
	vkCmdBindPipelineFn = nullptr;
	vkCmdPushConstantsFn = nullptr;
	vkCmdBindDescriptorSetsFn = nullptr;
	vkUpdateDescriptorSetsFn = nullptr;
	vkAllocateDescriptorSetsFn = nullptr;
	vkCreateDescriptorSetLayoutFn = nullptr;
	vkCreateDescriptorPoolFn = nullptr;
	vkCreateShaderModuleFn = nullptr;
	vkCreateQueryPoolFn = nullptr;
	vkDestroyQueryPoolFn = nullptr;
	vkCmdResetQueryPoolFn = nullptr;
	vkCmdWriteTimestamp2Fn = nullptr;
	vkGetQueryPoolResultsFn = nullptr;
	vkCreateSamplerFn = nullptr;
	vkDestroySamplerFn = nullptr;
	vkCmdPipelineBarrierFn = nullptr;
	vkCmdCopyBufferToImageFn = nullptr;

	s_IsLoaded = false;
}

void Lust::VKFunctions::LoadMockVulkanFunctions()
{
	if (s_IsLoaded)
		return;
}

bool Lust::VKFunctions::IsLoaded()
{
	return s_IsLoaded;
}

/*
vkCreateInstanceFn = ;
vkDestroyInstanceFn = ;
vkEnumeratePhysicalDevicesFn = ;
vkGetPhysicalDeviceFeaturesFn = ;
vkGetPhysicalDeviceFormatPropertiesFn = ;
vkGetPhysicalDeviceImageFormatPropertiesFn = ;
vkGetPhysicalDevicePropertiesFn = ;
vkGetPhysicalDeviceQueueFamilyPropertiesFn = ;
vkGetPhysicalDeviceMemoryPropertiesFn = ;
vkGetInstanceProcAddrFn = ;
vkGetDeviceProcAddrFn = ;
vkCreateDeviceFn = ;
vkDestroyDeviceFn = ;
vkEnumerateInstanceExtensionPropertiesFn = ;
vkEnumerateDeviceExtensionPropertiesFn = ;
vkEnumerateInstanceLayerPropertiesFn = ;
vkEnumerateDeviceLayerPropertiesFn = ;
vkGetDeviceQueueFn = ;
vkQueueSubmitFn = ;
vkQueueWaitIdleFn = ;
vkDeviceWaitIdleFn = ;
vkAllocateMemoryFn = ;
vkFreeMemoryFn = ;
vkMapMemoryFn = ;
vkUnmapMemoryFn = ;
vkFlushMappedMemoryRangesFn = ;
vkInvalidateMappedMemoryRangesFn = ;
vkGetDeviceMemoryCommitmentFn = ;
vkBindBufferMemoryFn = ;
vkBindImageMemoryFn = ;
vkGetBufferMemoryRequirementsFn = ;
vkGetImageMemoryRequirementsFn = ;
vkGetImageSparseMemoryRequirementsFn = ;
vkGetPhysicalDeviceSparseImageFormatPropertiesFn = ;
vkQueueBindSparseFn = ;
vkCreateFenceFn = ;
vkDestroyFenceFn = ;
vkResetFencesFn = ;
vkGetFenceStatusFn = ;
vkWaitForFencesFn = ;
vkCreateSemaphoreFn = ;
vkDestroySemaphoreFn = ;
vkCreateEventFn = ;
vkDestroyEventFn = ;
vkGetEventStatusFn = ;
vkSetEventFn = ;
vkResetEventFn = ;
vkCreateQueryPoolFn = ;
vkDestroyQueryPoolFn = ;
vkGetQueryPoolResultsFn = ;
vkCreateBufferFn = ;
vkDestroyBufferFn = ;
vkCreateBufferViewFn = ;
vkDestroyBufferViewFn = ;
vkCreateImageFn = ;
vkDestroyImageFn = ;
vkGetImageSubresourceLayoutFn = ;
vkCreateImageViewFn = ;
vkDestroyImageViewFn = ;
vkCreateShaderModuleFn = ;
vkDestroyShaderModuleFn = ;
vkCreatePipelineCacheFn = ;
vkDestroyPipelineCacheFn = ;
vkGetPipelineCacheDataFn = ;
vkMergePipelineCachesFn = ;
vkCreateGraphicsPipelinesFn = ;
vkCreateComputePipelinesFn = ;
vkDestroyPipelineFn = ;
vkCreatePipelineLayoutFn = ;
vkDestroyPipelineLayoutFn = ;
vkCreateSamplerFn = ;
vkDestroySamplerFn = ;
vkCreateDescriptorSetLayoutFn = ;
vkDestroyDescriptorSetLayoutFn = ;
vkCreateDescriptorPoolFn = ;
vkDestroyDescriptorPoolFn = ;
vkResetDescriptorPoolFn = ;
vkAllocateDescriptorSetsFn = ;
vkFreeDescriptorSetsFn = ;
vkUpdateDescriptorSetsFn = ;
vkCreateFramebufferFn = ;
vkDestroyFramebufferFn = ;
vkCreateRenderPassFn = ;
vkDestroyRenderPassFn = ;
vkGetRenderAreaGranularityFn = ;
vkCreateCommandPoolFn = ;
vkDestroyCommandPoolFn = ;
vkResetCommandPoolFn = ;
vkAllocateCommandBuffersFn = ;
vkFreeCommandBuffersFn = ;
vkBeginCommandBufferFn = ;
vkEndCommandBufferFn = ;
vkResetCommandBufferFn = ;
vkCmdBindPipelineFn = ;
vkCmdSetViewportFn = ;
vkCmdSetScissorFn = ;
vkCmdSetLineWidthFn = ;
vkCmdSetDepthBiasFn = ;
vkCmdSetBlendConstantsFn = ;
vkCmdSetDepthBoundsFn = ;
vkCmdSetStencilCompareMaskFn = ;
vkCmdSetStencilWriteMaskFn = ;
vkCmdSetStencilReferenceFn = ;
vkCmdBindDescriptorSetsFn = ;
vkCmdBindIndexBufferFn = ;
vkCmdBindVertexBuffersFn = ;
vkCmdDrawFn = ;
vkCmdDrawIndexedFn = ;
vkCmdDrawIndirectFn = ;
vkCmdDrawIndexedIndirectFn = ;
vkCmdDispatchFn = ;
vkCmdDispatchIndirectFn = ;
vkCmdCopyBufferFn = ;
vkCmdCopyImageFn = ;
vkCmdBlitImageFn = ;
vkCmdCopyBufferToImageFn = ;
vkCmdCopyImageToBufferFn = ;
vkCmdUpdateBufferFn = ;
vkCmdFillBufferFn = ;
vkCmdClearColorImageFn = ;
vkCmdClearDepthStencilImageFn = ;
vkCmdClearAttachmentsFn = ;
vkCmdResolveImageFn = ;
vkCmdSetEventFn = ;
vkCmdResetEventFn = ;
vkCmdWaitEventsFn = ;
vkCmdPipelineBarrierFn = ;
vkCmdBeginQueryFn = ;
vkCmdEndQueryFn = ;
vkCmdResetQueryPoolFn = ;
*/